[workspace]
authors = ["The Gammapy team"]
channels = ["conda-forge"]
name = "gammapy-recipes"
platforms = ["osx-arm64", "win-64", "linux-64", "osx-64"]
version = "0.1.0"

[tasks]
gammapy-data-download = "gammapy download datasets"

[dependencies]
sphinx = ">=8.2.3,<9"
sphinx-gallery = ">=0.19.0,<0.20"
pydata-sphinx-theme = ">=0.16.1,<0.17"
nbconvert = "*"
pandoc = ">=3.8.2,<4"

[feature.gp-background-model]
channels = ["conda-forge"]

[feature.gp-background-model.dependencies]
gammapy = "1.0.2.*"
python = "3.9.*"
scipy = "<1.12"
jupyter = "*"
matplotlib = "*"
tqdm = "*"

[feature.gp-background-model.tasks]
gammapy-data-download = "gammapy download datasets"
execute = { cmd = "jupyter nbconvert --execute recipes/background-model/background_model.ipynb --to rst", env = { GAMMAPY_DATA = "$PWD/gammapy-datasets/1.0.2/" } }

[feature.pulsar-gammapy]
channels = ["conda-forge"]

[feature.pulsar-gammapy.dependencies]
gammapy = "1.2.*"
python = "3.11.*"
scipy = "<1.12"
jupyter = "*"
pip = "*"

[feature.pulsar-gammapy.pypi-dependencies]
pint-pulsar = "~=1.0"

[feature.fit-psd-lightcurve]
channels = ["conda-forge"]

[feature.fit-psd-lightcurve.dependencies]
gammapy = "1.2.*"
python = "3.11.*"
scipy = "*"
jupyter = "*"
matplotlib = "*"

[feature.fit-psd-lightcurve.pypi-dependencies]
gammapy-sylc = { git = "https://github.com/cgalelli/gammapy_SyLC.git" }

[feature.gp-ts-vs-excess]
channels = ["conda-forge"]

[feature.gp-ts-vs-excess.dependencies]
gammapy = "1.0.2.*"
python = "3.9.*"
scipy = "<1.12"
jupyter = "*"

[feature.gp-interactive-model]
channels = ["conda-forge"]

[feature.gp-interactive-model.dependencies]
gammapy = "1.0.2.*"
python = "3.9.*"
jupyter = "*"
jupyterlab = "<=3.5.3"
scipy = "<1.12"
astropy = ">=4.0"
pandas = ">=1.1"
qgrid = "1.3.1.*"
ipywidgets = ">7.0"

[feature.gp-dark-matter]
channels = ["conda-forge"]

[feature.gp-dark-matter.dependencies]
gammapy = "1.0.2.*"
python = "3.9.*"
scipy = "<1.12"
jupyter = "*"

[feature.gp-mcmc]
channels = ["conda-forge"]

[feature.gp-mcmc.dependencies]
python = "3.10.*"
gammapy = "1.2.*"
jupyter = "*"
scipy = "1.8.0.*"
emcee = "3.1.4.*"
corner = "2.2.2.*"
zeus-mcmc = "2.5.4.*"

[environments]
gp-background-model = { features = ["gp-background-model"], no-default-feature = true }
pulsar-gammapy = { features = ["pulsar-gammapy"], no-default-feature = true }
fit-psd-lightcurve = { features = ["fit-psd-lightcurve"], no-default-feature = true }
gp-ts-vs-excess = { features = ["gp-ts-vs-excess"], no-default-feature = true }
gp-interactive-model = { features = ["gp-interactive-model"], no-default-feature = true }
gp-dark-matter = { features = ["gp-dark-matter"], no-default-feature = true }
gp-mcmc = { features = ["gp-mcmc"], no-default-feature = true }
